version: '3.8'

services:
  wordrepeaterbot:
    image: wordrepeaterbot
    container_name: wordrepeaterbot
    restart: always
    build:
      context: .
      dockerfile: Src/WordRepeaterBot/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_Kestrel__Certificates__Default__Path: fullchain.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: privkey.pem
      BotConfig__Host: ${BotConfig__Host}
      BotConfig__BotToken: ${BotToken}
      ConnectionStrings__WordRepeaterBotDb: ${ConnectionStrings__WordRepeaterBotDb}
    ports:
      - 5080:80
      - 8443:443
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    restart: always
    container_name: postgresql
    environment:
      POSTGRES_USER: sobol
      POSTGRES_PASSWORD: Marlo2344
    volumes:
      - ./volumes/postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  wordrepeaterbot-sender:
    container_name: wordrepeaterbot-sender
    build:
      context: .
      dockerfile: Src/WordRepeaterBot.Sender/Dockerfile
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.sender.schedule: "@hourly"
      ofelia.job-exec.sender.command: "dotnet WordRepeaterBot.Sender.dll"
    environment:
      ConnectionStrings__WordRepeaterBotDb: ${ConnectionStrings__WordRepeaterBotDb}
      BotToken: ${BotToken}
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia-job-runner
    restart: always
    depends_on:
      - wordrepeaterbot-sender
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_local
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: eskapte@mail.ru
  #     PGADMIN_DEFAULT_PASSWORD: Marlo2344
  #   volumes:
  #     - ./volumes/pgadmin_data:/var/lib/pgadmin
  #   ports:
  #     - 5431:80
  #   depends_on:
  #     - postgresql
        
