version: '3.8'

services:
  wordrepeaterbot:
    image: wordrepeaterbot
    build:
      context: .
      dockerfile: Src/WordRepeaterBot/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_Kestrel__Certificates__Default__Path: fullchain.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: privkey.pem
    ports:
      - 5080:80
      - 8443:443
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    container_name: postgresql_local
    environment:
      POSTGRES_USER: sobol
      POSTGRES_PASSWORD: Marlo2344
    # volumes:
    #   - ./volumes/postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_local
    environment:
      PGADMIN_DEFAULT_EMAIL: eskapte@mail.ru
      PGADMIN_DEFAULT_PASSWORD: Marlo2344
    # volumes:
    #   - ./volumes/pgadmin_data:/var/lib/pgadmin
    ports:
      - 5431:80
    depends_on:
      - postgresql
        
