name: Deploy

on:
  push:
    branches: [ master ]
    
jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Docker-compose build
#        run: docker-compose build
  deploy:
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.DEPLOY_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            git clone ${{ secrets.GIT_URL }} app;
            cd app;
            git checkout main;
            git fetch;
            git pull origin master;
            docker-compose --file docker-compose.yml down;
            echo BotConfig__Host=\"${{ secrets.BOT_CONFIG_HOST }}\" > .env;
            echo BotToken=\"${{ secrets.BOT_TOKEN }}\" >> .env;
            echo 'ConnectionStrings__WordRepeaterBotDb=${{ secrets.DB_CONNECTION_STRING }}' >> .env;
            echo 'PG_PASSWORD=${{ secrets.PG_PASSWORD }}' >> .env;
            pwd;
            echo "=== BUILD ===\n";
            docker-compose build --build-arg uid=`id -u` --build-arg gid=`id -g`;
            echo "=== UP ===\n";
            docker-compose up -d;
#            docker system prune -a