name: Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net core SDK 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.DEPLOY_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            git clone ${{ secrets.GIT_URL }} app;
            cd app;
            git checkout main;
            git fetch;
            git pull origin master;
            docker-compose --file docker-compose.yml down;
            echo BotConfig__Host=\"${{ secrets.BOT_CONFIG_HOST }}\" > .env;
            echo BotToken=\"${{ secrets.BOT_TOKEN }}\" >> .env;
            echo ConnectionStrings__WordRepeaterBotDb=\"${{ secrets.BOT_CONFIG_HOST }}\" >> .env;
            docker-compose build
            docker-compose --file docker-compose.yml up -d;
            docker system prune --all --force;