name: Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure environment variables
        run: |
          echo BotConfig__Host=\"${{ secrets.BOT_CONFIG_HOST }}\" > .env
          echo BotToken=\"${{ secrets.BOT_TOKEN }}\" >> .env
          echo ConnectionStrings__WordRepeaterBotDb=\"${{ secrets.BOT_CONFIG_HOST }}\" >> .env
      - name: Docker-Compose Remote Deployment
        uses: alex-ac/github-action-ssh-docker-compose@master
        with:
          ssh_host: ${{ secrets.DEPLOY_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          docker_compose_prefix: word-repeater-bot
          docker_compose_filename: ./docker-compose.yml